version: '3'

services:
  pg:
    image: bitnami/postgresql:12-debian-9
    container_name: gamea-pg
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: gamea
    ports:
      - 5435:5432
    networks:
      backend:
        ipv4_address: 172.21.4.12

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.4.0/24

volumes:
  data:
    driver: local